<a href="https://colab.research.google.com/github/Luis1161/Nuevo-c-digo/blob/main/Actividad_1_Laboratorio_Implementaci%C3%B3n_del_m%C3%A9todo_de_eliminaci%C3%B3n_gaussiana_con_pivotaje_parcial_escalado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Actividad 1:
Laboratorio. Implementación del método de eliminación gaussiana con pivotaje parcial escalado.**

**Escuela superior de ingeniería y tecnología fundación universitaria internacional de La Rioja.**

**Asignatura:** Álgebra y matematica discreta.

**Presentado por:** Luis Alberto Ospino Rico

**Docentes:** Dr. Marcos Chacon Castro, Iván Dario Maldonado Pasmiño.

**Fecha:** Marzo 02 del 2026.

**Enlace al google colab:** [Aquí](https://colab.research.google.com/drive/1UYyfIU8oJRDRh1bnKd0B6-SiFPP0U5bO?usp=sharing//)

**Laboratorio. Implementación del método de eliminación gaussiana con pivotaje parcial escalado**

#**Objetivos**

*-Aplicar los conceptos abordados en el tema 6 relacionados con eliminación gaussiana.*

*-Familiarizarse con el uso de cuadernos de Google Colaboratory combinando texto enriquecido, LaTeX y código ejecutable en un mismo documento*


#**Descripción de la actividad y pautas de elaboración**

**A continuación, se plantea un problema que se resuelve aplicado los conceptos y procedimientos vistos en el tema 6. Usa el lenguaje de programación Python en el entorno Google Colaboratory para resolver el problema. Escribe las expresiones matemáticas con LaTeX. El informe debe elaborarse en Google Colaboratory y entregarse únicamente como un solo archivo en formato PDF usando la opción Archivo/Imprimir del entorno y realizando los ajustes necesarios para garantizar la correcta visualización de todo el documento. La extensión máxima es de 10 páginas. En la entrega se debe indicar además el enlace al cuaderno de Google Colaboratory para comprobar el funcionamiento del programa. Asegúrate de compartir el archivo para que Cualquier persona con el enlace tenga acceso como Lector.**


#**Problema**

**A.** Crea una función que implemente el método de pivotaje parcial escalado. La función debe tener dos parámetros de entrada: la matriz de coeficientes del sistema, A, de orden n×n, y el vector de términos independientes, b, de orden n×1; y una salida: la matriz equivalente por filas, de orden n×(n+1), en su forma escalonada por filas. Tanto las matrices como los vectores deben ser objetos del tipo array de NumPy.

**B.**	Realiza pruebas de la función con cuatro sistemas de ecuaciones lineales que tengan dimensiones y soluciones diferentes. Incluye los siguientes casos: solución única, infinitas soluciones y sin solución.


#**Descripción de la actividad y pautas de elaboración**


A continuación, se plantea un problema que se resuelve aplicado los conceptos y procedimientos vistos en el tema 6. Usa el lenguaje de programación Python en el entorno Google Colaboratory para resolver el problema. Escribe las expresiones matemáticas con LaTeX. El informe debe elaborarse en Google Colaboratory y entregarse únicamente como un solo archivo en formato PDF usando la opción Archivo/Imprimir del entorno y realizando los ajustes necesarios para garantizar la correcta visualización de todo el documento. La extensión máxima es de 10 páginas. En la entrega se debe indicar además el enlace al cuaderno de Google Colaboratory para comprobar el funcionamiento del programa. Asegúrate de compartir el archivo para que cualquier persona con el enlace tenga acceso como Lector.


# **Introducción y objetivos**

El metodo de eliminación gaussiana con pivotaje parcial escalado nos permite resolver un sistema de ecuaciones lineales expresadas como Ax = b. Así, A corresponde a los coeficientes del sistema, x al  numero de variables, y b al vector de terminos independientes (o la igualdad). Consideramos que es el mejor método en cuanto a código se refiere. Porque al dejar el sistema de forma escalonada, el proceso se facilita tanto en la escritura de código como en la ejecución del mismo. Evita errores de redondeo y "alucinaciones" respecto al calculo.

Los objetivos de este trabajo consisten en entender a cabalidad como funciona el método de eliminación gaussiana con pivoteo parcial escalado no solo como teorema matemático aislado, sino como un método numérico que optimiza procesos informáticos y contribuye a la eficiencia del código y su escritura.






## **Desarrollo**

Como mencionamos anteriormente, en los sistemas lineales

$$
A\mathbf{x} = \mathbf{b}
$$


- $A \in \mathbb{R}^{n \times n}$
- $\mathbf{x} \in \mathbb{R}^n$
- $\mathbf{b} \in \mathbb{R}^n$

Él objetivo es encontrar el vector solución $\mathbf{x}$.

---

## **Los factores de escala**

Para cada fila se define el factor de escala:

$$
s_i = \max_{1 \le j \le n} |a_{ij}|
$$

Este valor se usa para evitar problemas numéricos.

---

## **Criterio de pivotaje**

En cada paso $k$ se selecciona como pivote la fila que maximiza:

$$
r_i = \frac{|a_{ik}|}{s_i}
$$

para $i = k, k+1, \dots, n$.

---

## **Eliminación**

Se debe calcular el multiplicador

$$
m_{ik} = \frac{a_{ik}}{a_{kk}}
$$

y actualizar las filas

$$
a_{ij}^{(nuevo)} = a_{ij} - m_{ik} a_{kj}
$$

$$
b_i^{(nuevo)} = b_i - m_{ik} b_k
$$

---

## **La sustitución regresiva**

Una vez obtenida la matriz triangular superior, el sistema se resuelve gracias a esta formula:

$$
x_i = \frac{1}{a_{ii}} \left( b_i - \sum_{j=i+1}^{n} a_{ij} x_j \right)
$$

---

## **Consideraciones que se deben tener**

Si $|a_{kk}| < 10^{-12}$, el pivote se considera numéricamente pequeño,lo que puede indicar que el sistema es singular, tiene infinitas soluciones o es inconsistente.




#**Escritura del código en python**

In [ ]:
# ==================================================
# LABORATORIO: ELIMINACIÓN GAUSSIANA CON PIVOTAJE PARCIAL ESCALADO
# Estudiantes: Miguel Eduardo Martínez Bustos, Luis Alberto Ospino Rico,
# Darlyn Jimena Naranjo Chaves
# Fecha: 2 de marzo del 2026
# ==================================================
"""
Nota: Nuestro código no usa números complejos o irracionales,
pero se ha escrito con cuidado para manejar casos de pivotes muy pequeños
(cercanos a cero) que podrían causar inestabilidad numérica.
En esos casos, el programa emite una advertencia y continúa con la eliminación."""
import numpy as np #Primero se importa la biblioteca numpy
# ------------------------------------------------------------------
# a) Función que implementa el método de pivotaje parcial escalado
# ------------------------------------------------------------------
def pivoteop_escalado(A, b): #Esta es nuestra función principal
    """
    A = matriz de coeficientes (n x n) como array de numpy
    b = vector de términos independientes (n) como array de numpy

    Y retorna
    Ab : matriz aumentada [A|b] en forma escalonada por filas (n x n+1)
    """
    A = A.astype(float) #Se escribe como float para de decimales
    b = b.astype(float)
    n = len(A)
    Ab = np.column_stack((A, b)) #Esta es la matriz aumentada [A|b]. Es decir, no tiene las variables.

    # Los factores de escala por fila
    s = np.max(np.abs(A), axis=1) #Nos permite detectar el valor máximo absoluto en cada fila de A, lo que se utiliza para el pivotaje escalado.

    # Proceso de eliminación
    for k in range(n-1): #Recorre cada columna del pivote desde 0 hasta n-2
        # Calcular los ratios para pivotaje escalado
        with np.errstate(divide='ignore', invalid='ignore'):
            ratios = np.where(s[k:] != 0, np.abs(Ab[k:, k]) / s[k:], 0)
        p = np.argmax(ratios) + k   # La fila pivote

        # Condición if para intercambiar filas si es necesario
        if p != k:
            Ab[[k, p]] = Ab[[p, k]]
            s[[k, p]] = s[[p, k]]

        # Si el pivote es cero. Sistema singular.
        if abs(Ab[k, k]) < 1e-12: #El "e" es la notación para números muy pequeños. Es para evitar las "alucinaciones, que mencionamos anteriormente".
            print(f"  (Pivote muy pequeño en paso {k}, por ende se omite)")
        # Eliminación
        for i in range(k+1, n):
            factor = Ab[i, k] / Ab[k, k] if abs(Ab[k, k]) > 1e-12 else 0
            Ab[i, k:] = Ab[i, k:] - factor * Ab[k, k:]
    return Ab
def sustitucionn_regresiva(Ab):
    """
    Para resolver el sistema triangular superior en forma escalonada.
    Retorna el vector solución o el None si no hay solución única.
    """
    n = len(Ab)
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        if abs(Ab[i, i]) < 1e-12:
            if abs(Ab[i, -1]) < 1e-12:
                print("  → Infinitas soluciones (fila de ceros)")
                return None
            else:
                print(f"  → Sin solución (fila {i}: 0 = {Ab[i, -1]:.2f})")
                return None
        suma = np.sum(Ab[i, i+1:n] * x[i+1:n])
        x[i] = (Ab[i, -1] - suma) / Ab[i, i]
    return x
def formatear_variables(sol):
    """
    Convierte el vector solución en variables de diferente nombre si es
    una matriz pequeña
    - Para 2 variables: x, y
    - Para 3 variables: x, y, z
    - Para más variables: x1, x2, x3, ...
    """
    n = len(sol)
    if n == 2:
        nombres = ['x', 'y']
    elif n == 3:
        nombres = ['x', 'y', 'z']
    else:
        nombres = [f'x{i+1}' for i in range(n)]
    return ', '.join([f"{nombres[i]} = {sol[i]:.6f}" for i in range(n)])

def probar_sistema(A, b, titulo):
    """Función auxiliar para probar los sistemas y mostrar resultados."""
    print("\n" + "="*60)
    print(f"PRUEBA: {titulo}")
    print("="*60)
    print("Matriz A:")
    print(A)
    print("Vector b:")
    print(b)

    Ab = pivoteop_escalado(A, b)
    print("\nMatriz escalonada [A|b]:")
    print(Ab)

    sol = sustitucionn_regresiva(Ab)
    if sol is not None:
        print("\nSolución:")
        print(formatear_variables(sol))
    else:
        print("\nEl sistema no tiene solución única.")
    print("="*60)


# ------------------------------------------------------------------
# b) Pruebas con cuatro sistemas diferentes hechos por nosotros.
# ------------------------------------------------------------------

# 1. Sistema con solución única (4x4)
A1 = np.array([[2, 1, -1, 3],
               [4, -3, 2, 1],
               [1, 2, 3, -1],
               [3, -1, 2, 4]])
b1 = np.array([5, 1, 2, 3])
probar_sistema(A1, b1, "Solución única para (4x4)")

# 2. Sistema con solución única (3x3)
A2 = np.array([[3, 2, -1],
               [2, -2, 4],
               [-1, 0.5, -1]])
b2 = np.array([1, -2, 0])
probar_sistema(A2, b2, "Solución única para (3x3)")

# 3. Sistema con infinitas soluciones (4x4)
A3 = np.array([[1, 2, 3, 4],
               [2, 4, 6, 8],
               [3, 6, 9, 12],
               [4, 8, 12, 16]])
b3 = np.array([4, 8, 12, 16])
probar_sistema(A3, b3, "Infinitas soluciones (filas dependientes)")

# 4. Sistema sin solución (3x3)
A4 = np.array([[1, 2, 3],
               [2, 4, 6],
               [1, 1, 1]])
b4 = np.array([4, 9, 3])
probar_sistema(A4, b4, "Sin solución. inconsistente")

# ------------------------------------------------------------------
#  La interfaz para que se puedan probar otros sistemas
# ------------------------------------------------------------------
print("\n" + "="*60)
respuesta = input("\n¿Desea probar un sistema personalizado? (si/no): ").strip().lower()
if respuesta == 'si':
    print("\n--- Ingreso de un sistema personalizado ---")
    n = int(input("Número de ecuaciones: "))
    A = np.zeros((n, n))
    print("Ingrese la matriz A, fila por fila (números separados por espacio):")
    for i in range(n):
        while True:
            fila = input(f"Fila {i+1}: ").strip().split()
            if len(fila) != n:
                print(f"Debe ingresar los {n} números que estableció.")
                continue
            try:
                A[i] = [float(x) for x in fila]
                break
            except ValueError:
                print("Solo números, por favor.")
    print("Ingrese el vector b (números separados por espacio):")
    while True:
        fila_b = input("b: ").strip().split()
        if len(fila_b) != n:
            print(f"Debe ingresar {n} números.")
            continue
        try:
            b = np.array([float(x) for x in fila_b])
            break
        except ValueError:
            print("Solo números, por favor.")
    probar_sistema(A, b, "Sistema personalizado")
else:
    print("\nOk, finalizando.")


PRUEBA: Solución única para (4x4)
Matriz A:
[[ 2  1 -1  3]
 [ 4 -3  2  1]
 [ 1  2  3 -1]
 [ 3 -1  2  4]]
Vector b:
[5 1 2 3]

Matriz escalonada [A|b]:
[[ 4.         -3.          2.          1.          1.        ]
 [ 0.          2.75        2.5        -1.25        1.75      ]
 [ 0.          0.         -4.27272727  3.63636364  2.90909091]
 [ 0.          0.          0.          3.27659574  1.0212766 ]]

Solución:
x1 = 1.246753, x2 = 1.155844, x3 = -0.415584, x4 = 0.311688

PRUEBA: Solución única para (3x3)
Matriz A:
[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
Vector b:
[ 1 -2  0]

Matriz escalonada [A|b]:
[[ 3.          2.         -1.          1.        ]
 [ 0.          1.16666667 -1.33333333  0.33333333]
 [ 0.          0.          0.85714286 -1.71428571]]

Solución:
x = 1.000000, y = -2.000000, z = -2.000000

PRUEBA: Infinitas soluciones (filas dependientes)
Matriz A:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Vector b:
[ 4  8 12 16]
  (Pivote muy pequeño e

# <Center> **Conclusiones y resultados de aprendizaje** </center>
La implementación del método de eliminación gaussiana con pivoteo parcial escalado nos permitió resolver sistemas de ecuaciones lineales de forma ordenada y eficiente. Las pruebas realizadas con sistemas de distintas dimensiones confirmaron que el programa no solo encuentra soluciones únicas, sino que también identifica correctamente cuando un sistema tiene infinitas soluciones o no tiene solución. Sin embargo, dados nuestros desconocimientos teóricos no pudimos implementar números irracionales o complejos. Nuestras operaciones están basadas solo en números reales no irracionales.
Sin embargo, como universitarios aprendimos gracias a este trabajo qué es una matriz, tipos de matrices, en qué consiste la eliminación gaussiana(con pivote o sin pivote y conocer como funciona y se realiza el procedimiento del mismo de manera no solo mecánica o tradicional, sino también algorítmica y funcional. Además, la dificultad inherente de dicho trabajo supuso aprender cómo se trabajan procesos dentro del lenguaje de programación de python, así como el uso crítico e interpretativo de los códigos y algoritmos proporcionados por el docente Maldonado, el docente Chacón y deepseek.

#**Bibliografía**

Deepseek. *Código base* https://github.com/Luis1161/Nuevo-c-digo/blob/main/deepseek_python_20260227_f07505.py

Cristobal, F. (2024). *Eliminación gaussiana con pivotaje parcial escalado* [Archivo de video]. Panopto. https://unir.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=feb9a091-83d0-4e64-bb81-aff1010f665d